# Generated by Django 3.0.5 on 2023-11-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida_personas', models.CharField(max_length=255)),
                ('unidad_medida_evento', models.CharField(max_length=255)),
                ('meta_programada_evento', models.IntegerField()),
                ('meta_realizada_evento', models.IntegerField()),
                ('meta_programada_personas', models.IntegerField()),
                ('meta_realizada_personas', models.IntegerField()),
            ],
            options={
                'db_table': 'metas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('nombre', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('duracion', models.TimeField()),
                ('objetivo', models.CharField(max_length=500)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paideacrud.MetaModelo')),
            ],
            options={
                'db_table': 'temas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('material', models.CharField(max_length=255)),
                ('cant_hombres', models.IntegerField()),
                ('cant_mujeres', models.IntegerField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paideacrud.Tema')),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['-id'],
            },
        ),
    ]
