# Generated by Django 3.0.5 on 2023-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paideacrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='duracion',
            field=models.CharField(max_length=255),
        ),
    ]
